# Generated by Django 3.0.1 on 2019-12-25 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_auto_20191225_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interfaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='接口名称', max_length=100, unique=True, verbose_name='接口名称')),
                ('leader', models.CharField(help_text='项目负责人', max_length=50, verbose_name='项目负责人')),
                ('tester', models.CharField(help_text='测试人员', max_length=50, verbose_name='测试人员')),
                ('desc', models.CharField(blank=True, default='', help_text='简要描述', max_length=200, null=True, verbose_name='简要描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间', verbose_name='更新时间')),
                ('project', models.ForeignKey(help_text='所属项目', on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='projects.Projects')),
            ],
            options={
                'verbose_name': '接口',
                'db_table': 'tb_interfaces',
            },
        ),
    ]
