# Generated by Django 3.0.1 on 2019-12-25 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='leader',
        ),
    ]
