# Generated by Django 3.0.1 on 2020-03-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0002_remove_interfaces_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='name',
            field=models.CharField(help_text='接口名称', max_length=200, unique=True, verbose_name='接口名称'),
        ),
    ]
