# Generated by Django 3.0.1 on 2020-02-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0004_interfaces_leader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='leader',
            field=models.CharField(default=0, help_text='项目负责人', max_length=50, null=True, verbose_name='项目负责人'),
        ),
    ]
