# Generated by Django 3.0.1 on 2020-02-18 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0005_auto_20200218_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='leader',
        ),
    ]
