# Generated by Django 3.0.1 on 2020-02-18 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interfaces', '0007_interfaces_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfaces',
            name='leader',
        ),
    ]
