# Generated by Django 3.0.1 on 2019-12-24 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目'},
        ),
        migrations.AlterModelTable(
            name='projects',
            table='tb_projects',
        ),
    ]
