# Generated by Django 3.0.1 on 2019-12-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191224_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='desc',
            field=models.CharField(blank=True, default='', help_text='简要描述', max_length=200, null=True, verbose_name='简要描述'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(help_text='项目名称', max_length=100, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='publish_app',
            field=models.CharField(help_text='发布应用', max_length=200, verbose_name='发布应用'),
        ),
    ]
