# Generated by Django 3.0.1 on 2020-03-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20191225_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(help_text='项目名称', max_length=200, unique=True, verbose_name='项目名称'),
        ),
    ]
